---

  - name: "Take Splunk cluster out of maintenance mode"
    command: /opt/splunk/bin/splunk disable maintenance-mode --answer-yes -auth "admin:vagrant"
    changed_when: False
    register: splunk_command_output

  - debug: msg="{{ splunk_command_output.stdout }}"
