---

  - name: "Put Splunk cluster into maintenance mode"
    command: /opt/splunk/bin/splunk enable maintenance-mode --answer-yes -auth "admin:vagrant"
    ignore_errors: True
    register: splunk_command_output

  - debug: msg="{{ splunk_command_output.stdout }}"
