---
# Target servers based on Splunk function (splunktion?)

- name: "Check All Servers Status"
  hosts: all_splunk_servers
  roles:
    - verify_status

- name: "Indexer Cluster Manager"
  hosts: splunk_manager
  roles:
    - splunk_cm_maintenance_mode_enable
    - reboot
    - verify_status
    - verify_splunk_status

- name: "Indexers"
  hosts: splunk_indexers
  serial: 1
  roles:
    - indexer_offline
    - reboot
    - verify_status
    - verify_splunk_status

- name: "Deployment Server"
  hosts: splunk_deployer
  roles:
    - indexer_offline
    - reboot
    - verify_status
    - verify_splunk_status

- name: "Search Heads"
  hosts: splunk_searchheads
  roles:
    - reboot
    - verify_status
    - verify_splunk_status
